version: '3'
services:

  web:
    build: .
    container_name: web_app_cont
    volumes:
      - .:/app
      - .ssh:/app/.ssh
      - static_volume:/app/project_core/static
      - media_volume:/app/project_core/media
    env_file:
      - .env
    command: >
      /bin/bash -c "
      python3 project_core/manage.py makemigrations --no-input
      && python3 project_core/manage.py migrate --no-input
      && python3 project_core/manage.py collectstatic --no-input
      && cd project_core
      && gunicorn --bind 0.0.0.0:8000 web_core.wsgi"
    ports:
      - "8000:8000"

  nginix:
    depends_on:
      - web
    image: nginx
    container_name: nginx_cont
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/project_core/static
    ports:
      - "80:80"
    restart: always


volumes:
  static_volume:
  media_volume:
