# Generated by Django 4.2 on 2023-04-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSeqCDPAgentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=255, verbose_name='Хост')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('ip_address', models.CharField(max_length=255, verbose_name='IP Адресс')),
                ('port', models.SmallIntegerField(default=0, verbose_name='Порт')),
            ],
            options={
                'verbose_name': 'CDP Агент',
                'verbose_name_plural': 'CDP Агенты',
            },
        ),
        migrations.CreateModel(
            name='InfoSeqLLDPAgentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=255, verbose_name='Хост')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('ip_address', models.CharField(max_length=255, verbose_name='IP Адресс')),
                ('port', models.SmallIntegerField(default=0, verbose_name='Порт')),
            ],
            options={
                'verbose_name': 'LLDP Агент',
                'verbose_name_plural': 'LLDP Агенты',
            },
        ),
        migrations.CreateModel(
            name='InfoSeqReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='InfoSeqUserCertficateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('password1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль1')),
                ('password2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль1')),
                ('create_at', models.DateTimeField(auto_now=True, verbose_name='Дата выдачи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуален')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='user_certificates', verbose_name='Сертификат')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='InfoSeqVPNRouteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назване')),
                ('description', models.TextField(verbose_name='Описание')),
                ('route', models.CharField(max_length=255, verbose_name='Путь')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'ВПН Сервисы',
            },
        ),
    ]
