# Generated by Django 4.2 on 2023-04-30 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dogma_users', '0001_initial'),
        ('dogma_infoseq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosequsercertficatemodel',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_certificate', to='dogma_users.dogmaemployee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='infosequsercertficatemodel',
            name='route',
            field=models.ManyToManyField(blank=True, related_name='routs', to='dogma_infoseq.infoseqvpnroutemodel', verbose_name='Сервис'),
        ),
        migrations.AddField(
            model_name='infoseqlldpagentmodel',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lldp_report', to='dogma_infoseq.infoseqreportmodel', verbose_name='Отчет'),
        ),
        migrations.AddField(
            model_name='infoseqcdpagentmodel',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cdp_report', to='dogma_infoseq.infoseqreportmodel', verbose_name='Отчет'),
        ),
    ]
