# Generated by Django 4.2 on 2023-04-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogma_infoseq', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infosequsercertficatemodel',
            old_name='name',
            new_name='title',
        ),
    ]
