# Generated by Django 4.2 on 2023-05-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogma_infoseq', '0004_infosequsercertficatemodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='country',
            field=models.SmallIntegerField(choices=[('RU', 'Ru')], default='RU'),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='key_size',
            field=models.SmallIntegerField(choices=[('2048', 'Large')], default='2048'),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='key_usage',
            field=models.SmallIntegerField(choices=[('tls-client', 'Tls')], default='tls-client'),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='locality',
            field=models.SmallIntegerField(choices=[('KRD', 'Krd'), ('MSK', 'Msk'), ('OMK', 'Omk')], default='KRD'),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='organization',
            field=models.SmallIntegerField(choices=[('DOGMA', 'Dogma')], default='DOGMA'),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='unit',
            field=models.SmallIntegerField(choices=[('DIS', 'Dis')], default='DIS'),
        ),
    ]
