# Generated by Django 4.2 on 2023-05-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogma_infoseq', '0005_alter_infosequsercertficatemodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='country',
            field=models.SmallIntegerField(choices=[('1', 'RU')], default='1'),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='key_size',
            field=models.SmallIntegerField(choices=[('1', '2048')], default='1'),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='key_usage',
            field=models.SmallIntegerField(choices=[('1', 'tls-client')], default='1'),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='locality',
            field=models.SmallIntegerField(choices=[('1', 'KRD'), ('2', 'MSK'), ('3', 'OMK')], default='1'),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='organization',
            field=models.SmallIntegerField(choices=[('1', 'DOGMA')], default='1'),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='unit',
            field=models.SmallIntegerField(choices=[('1', 'DIS')], default='1'),
        ),
    ]
