# Generated by Django 4.2 on 2023-05-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogma_infoseq', '0007_alter_infosequsercertficatemodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='state',
            field=models.SmallIntegerField(choices=[(1, '31')], default=1),
        ),
    ]
