# Generated by Django 4.2 on 2023-05-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogma_infoseq', '0008_alter_infosequsercertficatemodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='country',
            field=models.CharField(choices=[('RU', 'Ru')], default='RU', max_length=20),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='key_size',
            field=models.CharField(choices=[('2048', 'Large')], default='2048', max_length=20),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='key_usage',
            field=models.CharField(choices=[('tls-client', 'Tls')], default='tls-client', max_length=20),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='locality',
            field=models.CharField(choices=[('KRD', 'Krd'), ('MSK', 'Msk'), ('OMK', 'Omk')], default='KRD', max_length=20),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='organization',
            field=models.CharField(choices=[('DOGMA', 'Dogma')], default='DOGMA', max_length=20),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='state',
            field=models.SmallIntegerField(choices=[(31, 'Krd')], default=31),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='unit',
            field=models.CharField(choices=[('DIS', 'Dis')], default='DIS', max_length=20),
        ),
    ]
