# Generated by Django 4.2 on 2023-05-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogma_infoseq', '0009_alter_infosequsercertficatemodel_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosequsercertficatemodel',
            name='for_ipad',
            field=models.BooleanField(default=True, verbose_name='Планшет'),
        ),
        migrations.AddField(
            model_name='infosequsercertficatemodel',
            name='for_linux',
            field=models.BooleanField(default=True, verbose_name='Linux OS'),
        ),
        migrations.AddField(
            model_name='infosequsercertficatemodel',
            name='for_mac',
            field=models.BooleanField(default=True, verbose_name='MAC OS'),
        ),
        migrations.AddField(
            model_name='infosequsercertficatemodel',
            name='for_mobile',
            field=models.BooleanField(default=True, verbose_name='Мобильный'),
        ),
        migrations.AddField(
            model_name='infosequsercertficatemodel',
            name='for_pc',
            field=models.BooleanField(default=True, verbose_name='Windows OS'),
        ),
    ]
