# Generated by Django 4.2 on 2023-05-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogma_infoseq', '0010_infosequsercertficatemodel_for_ipad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи'),
        ),
    ]
