# Generated by Django 4.2 on 2023-05-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogma_infoseq', '0011_alter_infosequsercertficatemodel_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='for_ipad',
            field=models.BooleanField(default=False, verbose_name='Планшет'),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='for_linux',
            field=models.BooleanField(default=False, verbose_name='Linux OS'),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='for_mac',
            field=models.BooleanField(default=False, verbose_name='MAC OS'),
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='for_mobile',
            field=models.BooleanField(default=False, verbose_name='Мобильный'),
        ),
    ]
