# Generated by Django 4.2 on 2023-05-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogma_infoseq', '0012_alter_infosequsercertficatemodel_for_ipad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сертификат'),
        ),
    ]
