# Generated by Django 4.2 on 2023-05-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogma_infoseq', '0013_alter_infosequsercertficatemodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosequsercertficatemodel',
            name='repeated',
            field=models.BooleanField(default=False, verbose_name='Повторный'),
        ),
    ]
