# Generated by Django 4.2 on 2023-06-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogma_infoseq', '0014_infosequsercertficatemodel_repeated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infosequsercertficatemodel',
            name='for_ipad',
        ),
        migrations.RemoveField(
            model_name='infosequsercertficatemodel',
            name='for_linux',
        ),
        migrations.RemoveField(
            model_name='infosequsercertficatemodel',
            name='for_mac',
        ),
        migrations.RemoveField(
            model_name='infosequsercertficatemodel',
            name='for_mobile',
        ),
        migrations.RemoveField(
            model_name='infosequsercertficatemodel',
            name='for_pc',
        ),
        migrations.AddField(
            model_name='infosequsercertficatemodel',
            name='destination',
            field=models.CharField(choices=[('WINDOWS', 'Windows'), ('IOS', 'Ios'), ('ANDROID', 'Android'), ('IPAD', 'Ipad'), ('IPHON', 'Iphon'), ('LINUX', 'Linux')], default='WINDOWS', max_length=20),
        ),
    ]
