# Generated by Django 4.2.3 on 2023-07-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogma_infoseq', '0015_remove_infosequsercertficatemodel_for_ipad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infosequsercertficatemodel',
            name='certificate',
        ),
        migrations.AlterField(
            model_name='infosequsercertficatemodel',
            name='organization',
            field=models.CharField(choices=[('DOGMA', 'Dogma'), ('ZAPOLYARE', 'Zapolyare')], default='DOGMA', max_length=20),
        ),
    ]
