# Generated by Django 4.2 on 2023-06-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogma_users', '0002_dogmadepartment_dogmauserposition_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DogmaDepartment',
            new_name='DogmaEmployeeDepartment',
        ),
        migrations.RenameModel(
            old_name='DogmaUserPosition',
            new_name='DogmaEmployeePosition',
        ),
    ]
