# Generated by Django 4.2 on 2023-06-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogma_users', '0003_rename_dogmadepartment_dogmaemployeedepartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogmaemployee',
            name='str_department',
        ),
        migrations.RemoveField(
            model_name='dogmaemployee',
            name='str_position',
        ),
        migrations.AlterField(
            model_name='dogmaemployee',
            name='department',
            field=models.CharField(default=1, max_length=255, verbose_name='Подразделение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dogmaemployee',
            name='position',
            field=models.CharField(default=12, max_length=255, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DogmaEmployeeDepartment',
        ),
        migrations.DeleteModel(
            name='DogmaEmployeePosition',
        ),
    ]
